# Generated by Django 5.2.12 on 2026-03-25 23:52

import decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))]),
        ),
    ]
