# Generated by Django 5.2.12 on 2026-03-26 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_amount'),
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='pets.pet'),
        ),
    ]
